### ISSUE TITLE
Audio format discussion

### ISSUE THREAD

**Issue by nicolemon** [UTD-CRSS/audio.exploreapollo.org#1]
Need to design how requests are passed to audio server. Will likely need:
- audio file format (eg. mp3, ogg, wav, etc.)
- number of channels
- MET of interest

**Comment by austinpray** [comment]
So we should probably limit our formats to 
- ogg
- aac

based on 

![image](https://cloud.githubusercontent.com/assets/2192970/10298983/80b54b22-6baa-11e5-8d7f-ac2a70fe1112.png)
- https://en.wikipedia.org/wiki/HTML5_Audio#Supported_audio_coding_formats
- https://www.scirra.com/blog/44/on-html5-audio-formats-aac-and-ogg
- https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

mp3 technically requires a license to use and encode+decode stuff. So let's just do AAC and ogg.

**Comment by DarrenCattle** [comment]
aac technically still has a license although it is lenient. I vote for ogg just to be completely on the safe side.

http://www.w3schools.com/html/html5_audio.asp

only mp3, ogg, and wav are listed here by default

**Comment by austinpray** [comment]
All browsers don't support ogg. 

Also you only have to pay for AAC if you are selling a decoder or encoder 

> License fees are due on the sale of encoders and/or decoders only. There are no patent license fees due on the distribution of bit-stream encoded in AAC, whether such bit-streams are broadcast, streamed over a network, or provided on physical media.

**Comment by austinpray** [comment]
Also if anyone ever links to w3schools in this project again they are fired

**Comment by nicolemon** [comment]
It looks like the audio files we're getting are in wav format - I think it would be better to keep them as such and manipulate them as wav, but only convert them to ogg or AAC when returning it to the browser.

> Also if anyone ever links to w3schools in this project again they are fired

Where'd this happen?

**Comment by austinpray** [comment]
> I think it would be better to keep them as such and manipulate them as wav, but only convert them to ogg or AAC when returning it to the browser

:+1: agree

> Where'd this happen?

![image](https://cloud.githubusercontent.com/assets/2192970/10321387/f755b896-6c3d-11e5-8fc5-f931e54e1ae8.png)

@darrencattle deleted his comment from the shame.

**Comment by nicolemon** [comment]
We may not need the file format as a parameter - the server should be able to identify the browser making the playback request (right?) and we return ogg if it's Firefox, otherwise aac. So I think the only information needed during _moment_ creation is:
- channels of interest - to derive which files are needed
- MET of interest - to derive where in each file is needed

Mixing only happens when a _moment_ is created - the resulting wav file is cached, and streamed at request in the appropriate format.

Of course the derivations depend on how the audio files are organized (which is...?), but realistically those two items are all that's necessary.

**Comment by austinpray** [comment]
> the server should be able to identify the browser making the playback request (right?) 

Nope, this is not possible. Parsing user agent strings is a pretty serious anti-pattern and generally doesn't work. Also how is it feasible to keep track of what browsers can play what?

The HTML and the JavaScript on the client will determine what the proper audio format the browser can play.

For instance:

``` html
<audio controls="controls">
  Your browser does not support the <code>audio</code> element.
  <source src="https://audio.exploreapollo.org/stream?format=aac" type="audio/mp4">
  <source src="https://audio.exploreapollo.org/stream?format=ogg" type="audio/ogg">
</audio>
```

**Comment by nicolemon** [comment]
Okay. But basically the streaming format isn't considered until playback, since we're just working with the wav files during moment creation.

In any case, can we say there are two types of requests to the audio server: processing and playback? But then we want processing and playback to occur simultaneously such as when editing a moment. Like a larger-scale, more complicated version of [audiko.net]() (turn on your AdBlocker!), but completely different because they're editing just trimming a file. Rambling.

Anyway, I can't imagine needing any other parameters beyond format, channels, MET.

**Comment by austinpray** [comment]
So the format thing is extremely simple: https://github.com/UTD-CRSS/audio.exploreapollo.org/blob/eae847ca7dd3ac235c3deed31f4ce3c0ad6d7112/main.go#L85-L86

Right now we have: 

``` go
ffmpegArgs := []string{"-i", "-", "-f", "mp3", "-ab", "256k", "pipe:"}
ffmpegCommand := exec.Command(ffmpeg, ffmpegArgs...)
```

"mp3" is hardcoded here. We just need to map a parameter to where the "mp3" is. I'll go ahead and leave the implementation up to you. 

Spoiler alert:

``` go
query := r.URL().Query()
if (!query.Get("format")) {
  // format is required, return an error
}
format := query.Get("format")
// validate and sanitize format parameter, do not pass it to my server raw please

ffmpegArgs := []string{"-i", "-", "-f", format, "-ab", "256k", "pipe:"}
ffmpegCommand := exec.Command(ffmpeg, ffmpegArgs...)
```

**Comment by austinpray** [comment]
> In any case, can we say there are two types of requests to the audio server: processing and playback? But then we want processing and playback to occur simultaneously such as when editing a moment.

No there is only one type of request: "Play the audio for these given parameters". The code I have in the repo at this moment (eae847ca7dd3ac235c3deed31f4ce3c0ad6d711) mixes and streams the audio back to the browser in realtime. Basically chunks of the result are sent immediately as they are processed. Try it out: https://aqueous-garden-9236.herokuapp.com/stream.mp3

![image](https://cloud.githubusercontent.com/assets/2192970/10327406/7373eadc-6c6c-11e5-83ec-6b22678ca2ab.png)
